import { Component, OnInit } from '@angular/core';
import { NivelService } from '../service/nivel.service';

@Component({
  selector: 'app-curriculo',
  templateUrl: './curriculo.component.html',
  styleUrls: ['./curriculo.component.css']
})
export class CurriculoComponent implements OnInit {

  mapa: Map<number, Array<any>> = new Map<number, Array<any>>();

  constructor(
    private nivelService: NivelService
  ) { }

  ngOnInit() {
    for (let i = 1; i <= 10; i++) {
      this.mapa.set(i, CURRICULO[i]);
    }
    console.log(this.mapa);
  }

  getClass(disc: any) {
    let clazz = 'list-group-item';
    if (disc.stStatus === 'CURSADA') {
      clazz = clazz + ' cursado';
    } else {
      clazz = clazz + ' pendente';
    }
    return clazz;
  }

}

const CURRICULO =
{
  "1": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 40498,
      "nmNome": "Cálculo I",
      "sgCodicred": "95300-04",
      "sgCodi": "95300",
      "sgCred": "04",
      "cdNivel": 1,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 7749,
      "nmNome": "Desenho Técnico",
      "sgCodicred": "48319-04",
      "sgCodi": "48319",
      "sgCred": "04",
      "cdNivel": 1,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6657,
      "nmNome": "Introdução À Engenharia Mecânica",
      "sgCodicred": "4442S-02",
      "sgCodi": "4442S",
      "sgCred": "02",
      "cdNivel": 1,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6659,
      "nmNome": "Qualidade Dimensional                   ",
      "sgCodicred": "4442U-02",
      "sgCodi": "4442U",
      "sgCred": "02",
      "cdNivel": 1,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6080,
      "nmNome": "Química Geral",
      "sgCodicred": "4311P-04",
      "sgCodi": "4311P",
      "sgCred": "04",
      "cdNivel": 1,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    }
  ],
  "2": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6688,
      "nmNome": "Ciência Dos Materiais",
      "sgCodicred": "4443S-04",
      "sgCodi": "4443S",
      "sgCred": "04",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 25505,
      "nmNome": "Computação E Solução De Problemas I",
      "sgCodicred": "4621L-04",
      "sgCodi": "4621L",
      "sgCred": "04",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 40542,
      "nmNome": "Cálculo Ii",
      "sgCodicred": "95301-04",
      "sgCodi": "95301",
      "sgCred": "04",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 7756,
      "nmNome": "Desenho Técnico Ii",
      "sgCodicred": "48325-02",
      "sgCodi": "48325",
      "sgCred": "02",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6658,
      "nmNome": "Desenvolvimento De Projetos             ",
      "sgCodicred": "4442T-02",
      "sgCodi": "4442T",
      "sgCred": "02",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6660,
      "nmNome": "Disciplinas Eletivas                    ",
      "sgCodicred": "4442V-08",
      "sgCodi": "4442V",
      "sgCred": "08",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 5877,
      "nmNome": "Mecânica Fundamental",
      "sgCodicred": "42188-04",
      "sgCodi": "42188",
      "sgCred": "04",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6599,
      "nmNome": "Prática De Oficina",
      "sgCodicred": "4440K-04",
      "sgCodi": "4440K",
      "sgCred": "04",
      "cdNivel": 2,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    }
  ],
  "3": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 17056,
      "nmNome": "Cálculo Diferencial E Integral Iii",
      "sgCodicred": "4115P-02",
      "sgCodi": "4115P",
      "sgCred": "02",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 5876,
      "nmNome": "Eletromagnetismo                        ",
      "sgCodicred": "42187-04",
      "sgCodi": "42187",
      "sgCred": "04",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 7431,
      "nmNome": "Ferramentas Computacionais              ",
      "sgCodicred": "4610T-02",
      "sgCodi": "4610T",
      "sgCred": "02",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6703,
      "nmNome": "Materiais Cerâmicos",
      "sgCodicred": "4444B-02",
      "sgCodi": "4444B",
      "sgCred": "02",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6702,
      "nmNome": "Materiais Metálicos",
      "sgCodicred": "4444A-04",
      "sgCodi": "4444A",
      "sgCred": "04",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 20554,
      "nmNome": "Programação De Robos",
      "sgCodicred": "44647-02",
      "sgCodi": "44647",
      "sgCred": "02",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6709,
      "nmNome": "Termodinâmica Aplicada",
      "sgCodicred": "4444H-04",
      "sgCodi": "4444H",
      "sgCred": "04",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 17058,
      "nmNome": "Álgebra Matricial",
      "sgCodicred": "4115S-02",
      "sgCodi": "4115S",
      "sgCred": "02",
      "cdNivel": 3,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ],
  "4": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 17057,
      "nmNome": "Cálculo Diferencial E Integral Iv",
      "sgCodicred": "4115R-04",
      "sgCodi": "4115R",
      "sgCred": "04",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 5792,
      "nmNome": "Dinâmica Do Corpo Rígido",
      "sgCodicred": "4210B-04",
      "sgCodi": "4210B",
      "sgCred": "04",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6878,
      "nmNome": "Eletrotécnica - Em",
      "sgCodicred": "4453G-02",
      "sgCodi": "4453G",
      "sgCred": "02",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6705,
      "nmNome": "Fundição",
      "sgCodicred": "4444D-02",
      "sgCodi": "4444D",
      "sgCred": "02",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 40565,
      "nmNome": "Matemática Aplicada",
      "sgCodicred": "95305-04",
      "sgCodi": "95305",
      "sgCred": "04",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6706,
      "nmNome": "Materiais Poliméricos",
      "sgCodicred": "4444E-02",
      "sgCodi": "4444E",
      "sgCred": "02",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 5879,
      "nmNome": "Ondas E Física Moderna",
      "sgCodicred": "42190-04",
      "sgCodi": "42190",
      "sgCred": "04",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 40563,
      "nmNome": "Probabilidade E Estatística",
      "sgCodicred": "95304-04",
      "sgCodi": "95304",
      "sgCred": "04",
      "cdNivel": 4,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ],
  "5": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 13451,
      "nmNome": "Humanismo E Cultura Religiosa           ",
      "sgCodicred": "11521-04",
      "sgCodi": "11521",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6710,
      "nmNome": "Mecanismos E Dinâmica De Máquinas",
      "sgCodicred": "4444J-04",
      "sgCodi": "4444J",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6712,
      "nmNome": "Mecânica Dos Fluidos",
      "sgCodicred": "4444L-04",
      "sgCodi": "4444L",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6480,
      "nmNome": "Resistência Dos Materiais I - Em",
      "sgCodicred": "4421R-04",
      "sgCodi": "4421R",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6713,
      "nmNome": "Soldagem                                ",
      "sgCodicred": "4444M-04",
      "sgCodi": "4444M",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6711,
      "nmNome": "Usinagem                                ",
      "sgCodicred": "4444K-04",
      "sgCodi": "4444K",
      "sgCred": "04",
      "cdNivel": 5,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    }
  ],
  "6": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 5569,
      "nmNome": "Cálculo Numérico A",
      "sgCodicred": "4113S-04",
      "sgCodi": "4113S",
      "sgCred": "04",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10630,
      "nmNome": "Eletrônica Básica - Em",
      "sgCodicred": "4453U-02",
      "sgCodi": "4453U",
      "sgCred": "02",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10585,
      "nmNome": "Engenharia Da Qualidade                 ",
      "sgCodicred": "4444P-02",
      "sgCodi": "4444P",
      "sgCred": "02",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10587,
      "nmNome": "Escoamentos Viscosos                    ",
      "sgCodicred": "4444S-02",
      "sgCodi": "4444S",
      "sgCred": "02",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 7013,
      "nmNome": "Gestão Empresarial Para Engenharia",
      "sgCodicred": "44721-02",
      "sgCodi": "44721",
      "sgCred": "02",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10583,
      "nmNome": "Resistência Dos Materiais Ii - Em",
      "sgCodicred": "4423G-04",
      "sgCodi": "4423G",
      "sgCred": "04",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10588,
      "nmNome": "Transferência De Calor",
      "sgCodicred": "4444T-04",
      "sgCodi": "4444T",
      "sgCred": "04",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10586,
      "nmNome": "Vibrações Mecânicas",
      "sgCodicred": "4444R-04",
      "sgCodi": "4444R",
      "sgCred": "04",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 13446,
      "nmNome": "Ética E Cidadania",
      "sgCodicred": "1501A-04",
      "sgCodi": "1501A",
      "sgCred": "04",
      "cdNivel": 6,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ],
  "7": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10590,
      "nmNome": "Conformação Mecânica",
      "sgCodicred": "4444V-04",
      "sgCodi": "4444V",
      "sgCred": "04",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2020/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10589,
      "nmNome": "Elementos De Máquinas",
      "sgCodicred": "4444U-04",
      "sgCodi": "4444U",
      "sgCred": "04",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": true,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10596,
      "nmNome": "Fenômenos De Convecção",
      "sgCodicred": "4445D-02",
      "sgCodi": "4445D",
      "sgCred": "02",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10594,
      "nmNome": "Manutenção Industrial",
      "sgCodicred": "4445A-02",
      "sgCodi": "4445A",
      "sgCred": "02",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10592,
      "nmNome": "Projeto Mec. Assist. Por Computador (Cad)",
      "sgCodicred": "4444X-02",
      "sgCodi": "4444X",
      "sgCred": "02",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10593,
      "nmNome": "Resistência Dos Materiais Iii",
      "sgCodicred": "4444Y-04",
      "sgCodi": "4444Y",
      "sgCred": "04",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10595,
      "nmNome": "Sistemas Fluidomecânicos",
      "sgCodicred": "4445B-04",
      "sgCodi": "4445B",
      "sgCred": "04",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10591,
      "nmNome": "Sistemas Robotizados - Em               ",
      "sgCodicred": "4444W-02",
      "sgCodi": "4444W",
      "sgCred": "02",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10688,
      "nmNome": "Ética E Exercício Profissional Da Engenharia",
      "sgCodicred": "44792-02",
      "sgCodi": "44792",
      "sgCred": "02",
      "cdNivel": 7,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2020/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ],
  "8": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10600,
      "nmNome": "Engenharia De Controle                  ",
      "sgCodicred": "4445H-02",
      "sgCodi": "4445H",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 27829,
      "nmNome": "Engenharia E Segurança Do Trabalho",
      "sgCodicred": "4471Y-02",
      "sgCodi": "4471Y",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 27828,
      "nmNome": "Engenharia Econômica",
      "sgCodicred": "4471X-02",
      "sgCodi": "4471X",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10599,
      "nmNome": "Instrumentação E Medição",
      "sgCodicred": "4445G-04",
      "sgCodi": "4445G",
      "sgCred": "04",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10601,
      "nmNome": "Integração Mecânica Experimental",
      "sgCodicred": "4445J-02",
      "sgCodi": "4445J",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10602,
      "nmNome": "Manufatura Assistida Por Computador (Cam)",
      "sgCodicred": "4445L-02",
      "sgCodi": "4445L",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10598,
      "nmNome": "Mecânica Do Contínuo",
      "sgCodicred": "4445F-02",
      "sgCodi": "4445F",
      "sgCred": "02",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10597,
      "nmNome": "Máquinas Térmicas",
      "sgCodicred": "4445E-04",
      "sgCodi": "4445E",
      "sgCred": "04",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10603,
      "nmNome": "Sistemas De Compressao Industrial       ",
      "sgCodicred": "4445M-04",
      "sgCodi": "4445M",
      "sgCred": "04",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": true,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6597,
      "nmNome": "Trocadores De Calor                     ",
      "sgCodicred": "4440H-04",
      "sgCodi": "4440H",
      "sgCred": "04",
      "cdNivel": 8,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/1",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ],
  "9": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10605,
      "nmNome": "Automação Industrial - Em",
      "sgCodicred": "4445P-02",
      "sgCodi": "4445P",
      "sgCred": "02",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10606,
      "nmNome": "Controle Hidráulico E Pneumático",
      "sgCodicred": "4445R-04",
      "sgCodi": "4445R",
      "sgCred": "04",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10607,
      "nmNome": "Engenharia Assist. Por Computador (Cae)",
      "sgCodicred": "4445T-02",
      "sgCodi": "4445T",
      "sgCred": "02",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10609,
      "nmNome": "Estágio Supervisionado - Em (190 Hrs)",
      "sgCodicred": "4445V-02",
      "sgCodi": "4445V",
      "sgCred": "02",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6700,
      "nmNome": "Geração E Utilização Do Vapor",
      "sgCodicred": "44449-04",
      "sgCodi": "44449",
      "sgCred": "04",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": "2019/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10610,
      "nmNome": "Projeto Mecânico",
      "sgCodicred": "4445W-04",
      "sgCodi": "4445W",
      "sgCred": "04",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": true,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10608,
      "nmNome": "Refrigeração E Ar Condicionado",
      "sgCodicred": "4445U-04",
      "sgCodi": "4445U",
      "sgCred": "04",
      "cdNivel": 9,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": true,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    }
  ],
  "10": [
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 19054,
      "nmNome": "Atividades Complementares (120 Horas)   ",
      "sgCodicred": "44028-00",
      "sgCodi": "44028",
      "sgCred": "00",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "LIBERADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10613,
      "nmNome": "Controle De Qualidade Industrial        ",
      "sgCodicred": "4446B-02",
      "sgCodi": "4446B",
      "sgCred": "02",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 27839,
      "nmNome": "Engenharia Ambiental I",
      "sgCodicred": "4481Y-02",
      "sgCodi": "4481Y",
      "sgCred": "02",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 4063,
      "nmNome": "Fundamentos De Economia Para Engenharia ",
      "sgCodicred": "2512A-02",
      "sgCodi": "2512A",
      "sgCred": "02",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "CURSADA",
      "txCursado": null,
      "txPlanejado": null,
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 6627,
      "nmNome": "Projeto De Produto                      ",
      "sgCodicred": "4441F-04",
      "sgCodi": "4441F",
      "sgCred": "04",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": false,
      "listTipoPedidoAluno": null
    },
    {
      "retorno": null,
      "mensagem": null,
      "cdDisciplina": 10612,
      "nmNome": "Trabalho De Conclusão De Curso - Em",
      "sgCodicred": "4446A-02",
      "sgCodi": "4446A",
      "sgCred": "02",
      "cdNivel": 10,
      "tipoDisciplina": null,
      "idTipoDisciplina": null,
      "nrCreditosPre": null,
      "stStatus": "PENDENTE",
      "txCursado": null,
      "txPlanejado": "2021/2",
      "txCorequisito": null,
      "cdCoRequisito": null,
      "disciplinasPreRequisito": null,
      "disciplinasSubstitutas": null,
      "disciplinasCoRequisitos": null,
      "disciplinasRequisitosEspeciais": null,
      "tipoRequisito": [],
      "turmas": [],
      "txTipoDisciplina": null,
      "cdGrupo": null,
      "cdTipoDisciplina": null,
      "qtCargaHoraria": null,
      "temPreRequisito": false,
      "temCoRequisito": false,
      "temRequisitoEspecial": false,
      "temSubstituta": true,
      "listTipoPedidoAluno": null
    }
  ]
}